### ISSUE TITLE
Sparky - unable to connect via usb with >= 1.6

### ISSUE THREAD

**Issue by emdzej** [cleanflight/cleanflight#450]
After flashing Sparky with cleanflight 1.6 or above OS dosn't recognize the board in VCP mode anymore.
Tried different flash methods:
- dfu-util under OSX (including mass-erase)
- defuse under Win
Binaries taken either from releases page (hex converted using filemgr) or self-compiled. Every time the result is the same. OS reports bad USB descriptor - under Windows, or enumeration failed under OSX.

Flashing back v1.5 resolves the issue

**Comment by hydra** [comment]
rev1 or rev2?

**Comment by hydra** [comment]
Both of my two sparkys are working with latest 1.7.0 release candidate.

**Comment by emdzej** [comment]
TauLabs GCS is reporting rev 2. I know that's weird, but tried many approaches with no luck, unless I'm missing something obvious.

**Comment by hydra** [comment]
please can identify the revision visually - the differences are here:

https://github.com/TauLabs/TauLabs/wiki/Sparky

some newer binaries have been built which corrected a problem with sbus port selection.  please can you try with the latest release candidate?

**Comment by hydra** [comment]
Might be related to #452

**Comment by emdzej** [comment]
Small update. So it's definitely an earlier revision (with 4 pin receiver port). I have downloaded the latest compiled binary from the releases and it worked this time. Then I've tried to compile the binary and flash it and it did not. (No luck with 1.6 though) 

The 1.7 binary downlaoded and 1.7 compiled differ - if this helps. Maybe there's something wrong with my toolchain, although no compilation errors occur.

**Comment by hydra** [comment]
ok, unable to replicate the problem here.  yes, every time you compile it you will get a different file since the date/time are embedded in the binary.  i'm using gcc 4.8, not 4.9.

Closing since latest release version works.

GCC 4.9 issues will be addressed sepatately but can reference this issue if needed.
