### PR TITLE
Enable self-leveling at minimum throttle

### PR DESCRIPTION
**Pull request by timkostka**
Previously, at minimum throttle, the quad would do absolutely no self-leveling
and simply run the motors at constant minthrottle.  This allowed the chance
for the quad to lose control during flight if the throttle was set to minimum,
say, to drop from a high altitude to a lower one.

With this edit, the quad will still self-level at minimum throttle when armed,
allowing for safe decents from altitude.  To prevent motors spinning when
arming/disarming, the yaw input is ignored if the throttle is at minimum and
we're using the sticks to arm/disarm.  I believe that was the intent of the
original code which also had the unfortunate side effect of disabling self-leveling.

Also renamed isUsingSticksForArming->areUsingSticksToArm and isUsingSticksToArm->useSticksToArm.

### CODE REVIEW

**Comment by thenickdude** [comment]
What happens if the quad is sitting on the ground at an angle, and you arm? Will this cause it to suddenly do something weird like try to pivot around to level itself?

**Comment by timkostka** [comment]
When throttle is low, the self-leveling is pretty tame.  I armed it at about 20 degrees off of horizontal and , while it does does try to level itself, it doesn't actually give the motors enough power to do so.  The amount it can self-level when armed is all governed within the PID routines, and it'll only try to do so in HORIZON or ANGLE mode.

**Comment by hydra** [comment]
yeah, so as I understand this.  If you land on unlevel ground and want to take off, then take of in acro mode and switch to auto-level mode.

i think this will require a little field testing before merging to make sure the behavior is what we want.

**Comment by timkostka** [comment]
I probably have about 15 batteries with this firmware without issue.  Taking off is not a problem.  You can sometimes get a small bounce when landing in horizon/angle mode as it tries to keep level, but it lands fine.

The nice thing is being able to descend at minimum throttle without having the quad flip over.  This is how the other FCs that I'm familiar with behave (Naza, Blade, OpenPilot).

**Comment by ProDrone** [comment]
For this purpose i use a switch that raises throttle command to mincheck + 1 value. When copter is disarmed it adds the safety that you cannot arm by accident (on the ground) or disarmed by accident (in the air). The control loops are always active when the switch is ON after arming. It is even possible to do a flip during free fall with throttle at minimum. I have used this for a.5 year and don not want to be without it. Up to now i modified all FC software i used for personal use.

**Comment by timkostka** [comment]
@ProDrone, Are you suggesting a change?  If this commit goes in, it isn't going to change the way you're currently doing things.  It will still behave as it currently does under your configuration.  If you're at mincheck+1, the sticks will not arm or disarm on full left/right yaw.

Alternatively, if the request goes through, you could also set an ARM flight mode switch and get the same functionality with a less TX programming.

**Comment by ProDrone** [comment]
@timkosta I just wanted to add that i also missed the stability on descents at minimum throttle (and found a solution that works for me), but I always fly in acro mode. Your modification seems to only apply to level modes. Descending with throttle below mincheck normally causes the control loops to go inactive. How will your modification behave when motor stop at minimum throttle is enabled?

**Comment by thenickdude** [comment]
It seems like it applies to all modes, not just self-levelling modes. All
it does is make the region below min_check on the throttle be exactly the
same as the region above it from a motor behaviour perspective, there is no
longer a sudden cut-off where the control of the motors to maintain your
commanded rotation / level fails.

When "MOTOR_STOP" is enabled, the behaviour is the same as it used to be,
the motors stop at low throttle.

**Comment by ledvinap** [comment]
IMO the @ProDrone approach is superior, only drawback is that it requires switch on transmitter and configurable mixer.

**Comment by timkostka** [comment]
Using another switch also works.  One drawback is if you try to disarm but you forgot to flip that switch back, the quad will try to yaw a ton instead of disarming.  I did that many times before switching to this solution.

**Comment by ledvinap** [comment]
It seems that on badly tuned pids, high gyro noise and side wind it is almost impossible to descend. Command necessary for leveling+noise is enough to hold altitude. I'll analyze blackbox...

If leveling is always enabled without possibility to override minimum throttle, only option will be disarming in-flight (with no possibility to arm again if small-angle is enabled).

**Comment by thenickdude** [comment]
I'd love to see that log, that sounds like quite an extraordinary situation!

**Comment by ledvinap** [comment]
Hmm .. turned on baro mode by mistake. So in baro mode with minimum throttle. Some tuning should fix it ...

**Comment by johnlenfr** [comment]
Is this PR is available in the v1.7.0 ?
Would like to test it because when in 4S, at minimum throttle, my quad is falling weird.

Would like to test if it is better with this PR.

**Comment by timkostka** [comment]
@johnlenfr, it is not in any releases yet.  I can make a binary for you after work, in about 12 hours.  Which board do you have?  Naze32?

Right now at minimum throttle, the PID algorithm is inactive and so the quad will be unstable.  That's likely what you're seeing.

**Comment by johnlenfr** [comment]
@timkostka : thanks, it will be very nice if you can do the binary, or put here with a link the 3 modified files, then I will do the hex file by myself.
Yes, I have the Naze32 board.
Would like to test it if it works I will say to you. 
I only use Naze32, without any other stuff like gps or baro.

**Comment by timkostka** [comment]
Hm... I cannot figure out how to update my fork to 1.7 or to apply my PR to my local copy of cleanflight.  Can you use the "files changed" tab to see what changed and apply it locally?  There are only a few edits.

If I have more time tomorrow maybe I'll try again.

**Comment by johnlenfr** [comment]
@timkostka : yes I don't know why I don't think of that before. I will use the file change tab and make changes with edits.

I'll keep your informed.

**Comment by johnlenfr** [comment]
@timkostka 
I tried to compile with fw1.7.0 but have the warning: implicit declaration of function 'areUsingSticksToArm' for line 523 in .../src/main/mw.c

I think you have to change line 216 of rc_controls.h: "bool areUsingSticksToArm(void);" at the same time you change rc_controls.c

Will tests on flight this evening.

**Comment by johnlenfr** [comment]
First test is ok, landing with autolevel is nice:
https://www.youtube.com/watch?v=SkNfXESNAi8

More tests this week end on the field...

**Comment by timkostka** [comment]
@johnlenfr, Thank you for testing this out.  I appreciate the work.  The PR was made about a month ago, glad to see it will works (mostly) with the changes.

I do strongly feel that the PID controllers should be active as long as the quad is armed, which is the reason behind the change.

**Comment by johnlenfr** [comment]
Tested on the field and approved!

**Comment by hydra** [comment]
I still need to try this myself. Not been able to fly much recently, not forgotten.

**Comment by johnlenfr** [comment]
Maybe it would be nice to have the choice between level or not?
i.e. create a CLI variable named set_autolevel = [0]/[1].
Some will prefers to have autolevel, others not.
Both will be satisfied.

**Comment by timkostka** [comment]
Maybe.  But when would you want the PIDs to be disabled?  I just didn't see
a use case for that.

The title of this issue is perhaps a bit misnamed, since it doesn't enable
auto-level or anything.  Maybe it should be "keep pids enabled even at
minimum throttle".

**Comment by ledvinap** [comment]
@timkostka : Until takeoff, it makes sense to have PIDs disabled. I terms in controller will accumulate error that can't be compensated, so some motor will spin up (until I term saturates).

One possible improvement is to enable PIDs only after throttle is increased first time after arming. Currently I have minimum throttle latch implemented in mixer (with override on rudder trim right switch) and it works great.

**Comment by johnlenfr** [comment]
I'm agree to your choice, I prefer to have PID always enabled.
But maybe some will don't want it.
So because I want it, if everyone is satisfied, the PR will be accepted.

**Comment by timkostka** [comment]
I agree, having a one-time latch that switches the first time you throttle
up might make sense.  I can add that to the PR if that's the consensus.
That would eliminate issues with the I term.

I know the default pid has no such issue, but I haven't tested the others
that have been added recently.

**Comment by johnlenfr** [comment]
Ok, so, if I understand, when you armed, ie the throttle is at 0, moving roll and pitch will have no effect until you first start to launch the quad. Then in flight, if you put the throttle at 0, PID were still enabled.

Is that correct?

**Comment by timkostka** [comment]
@johnlenfr, @ledvinap, I planned to just zero out the I term, since the P and D terms should be okay on their own.  However...

The code already resets the I term in the PID algorithm when throttle is low.  In mw.c:

    if (throttleStatus == THROTTLE_LOW) {
        resetErrorAngle();
        resetErrorGyro();
    }

So, no change needed because it's already in there.  That would also explain why I'm not seeing an issue even when the quad is on non-level ground.  :)

I think the PR should be added as-is unless someone experiences issues during flight.  I'm happy to add the one-time latch on takeoff if it's shown as necessary.

**Comment by johnlenfr** [comment]
@timkostka nice!
And is it compatible with all the pid_controler's ?

**Comment by johnlenfr** [comment]
Is it possible to merge this PR in the next fw?

**Comment by johnlenfr** [comment]
I gave the modified firmware with your improvements to 2/3 guys around me.
This new firmware opens new perspectives and new figures combos :)

They all (and more) have adopted this new feature :D

**Comment by hydra** [comment]
1. can you update this PR so it merges cleanly?  rebase the commits onto the current codebase.
2. can you add  new cli command that can enable this, call it `autolevel_at_low_throttle' or something suitable.
3. can you update the PR to include documentation updates that detail the behaviour and alternative behaviour and how to enable the alternative behaviour via the new cli command.

after that I will merge the feature, it seems useful.

**Comment by hydra** [comment]
please also rever the changes to 'rc_controls.c' 

IMHO:

`if (areUsingSticksToArm()) ...`

is not as good as

`if (isUsingSticksToArm()) ...`

if you have a better idea than either of those then please do that as a seperate PR from this one so that the change doesnt hold up this PR.

**Comment by timkostka** [comment]
I added the CLI command but I don't know a good way to access it from within "mixer.c":

                     } else if (masterConfig.disable_pid_at_min_throttle != 0) {
                                ^
    ./src/main/flight/mixer.c:691:28: note: each undeclared identifier is reported only once for each function it appears in

**Comment by markminer** [comment]
timkostka,

Anxiously awaiting this feature! 

mark miner

**Comment by timkostka** [comment]
I tested the following on my Naze32 acro board to ensure it worked as expected:
* I used defaults to see if pids responded at zero throttle.
* I set "disable_pid_at_min_throttle = 1" to see if pids no longer responded (previous behavior).
* I enabled the "motor_stop" feature to see if motors didn't spin when armed.

All tests passed.  I did not do as much flight testing on this as I did on the original PR, but nothing substantial changed between the two apart from the CLI command, which I tested.

Should be good to merge.

**Comment by timkostka** [comment]
Okay, I added it into the CLI doc.  I don't really know where else to put it.

**Comment by timkostka** [comment]
Okay, it fails on one CC3D build, but otherwise works fine.  CC3D is running into flash storage issues for a number of other builds when building with "opbl=yes" whatever that means.

```
/usr/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: obj/main/cleanflight_CC3D.elf section `.data' will not fit in region `FLASH'
/usr/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 20 bytes
collect2: error: ld returned 1 exit status
make: *** [obj/main/cleanflight_CC3D.elf] Error 1
```

I can't really make more more room for the code in this PR.  That should be a separate PR.

**Comment by hydra** [comment]
Merged.  I squashed the commits.

Please also see:
ed434fe47b5865dd55907a59c0bfb84aac62dce5
and:
4a12d00d1e23fbab5f7c0effda5bf07b79f7a1d5
