### ISSUE TITLE
AfroFlight 32 (naze32) 2.5.0 and 2.4.0 does not connect

### ISSUE THREAD

**Issue by MauroMombelli** [cleanflight/cleanflight#3075]
**Describe the bug**
I updated the board to 2.5.0 without issue, with full flash erase, but then the red led stay on and i cant connect, even after power cycling. Then tried 2.4.0, same issue, then 2.3.2, and with that one seems to work fine (connect, the imu return good orientation).

**To Reproduce**
Flash v2.5.0 or 2.4.0 to a AfroFlight 32 (Naze 32 clone, so i expect to be a issue for all Naze)

**Comment by marcopovitch** [comment]
Same for me with AfroFlight32 rev5. The blue led stays on. Need to reflash using the bootloader  shortcut pins. 
The higher working firmware I was enable to flash  is also 2.3.2

**Comment by MauroMombelli** [comment]
somewhere i read they are dropping/dropped support for F103 architecture, @hydra am I correct?

**Comment by schugabe** [comment]
Same issue for the afromini v2.

**Comment by schugabe** [comment]
git bisect shows that with 8b985285901031e9a770a08582ad6cc07d97cb97 the AFROMINI Target stopped working (nothing major changed with this commit).
Next I tried to disable some features and compile the current master and it starts working again. So I'd guess that the current config does not fit in the F1.

**Comment by MauroMombelli** [comment]
What do you mean by config is too big? Firmware too big should cause a
compilation error., unless we have a stack overflow.
I see in the commit they switch from driver/time.h to common/drive.h; maybe
that has a bug?

**Comment by hydra** [comment]
@MauroMombelli F1 support is still in the codebase, I'd like to support it as long as possible.  Yesterday I did some fixes to allow the AFROMINI to compile but it doesn't fit in flash still.

I have some plans to allow the firmware to fit and if these plans come to fruition we can revisit this.

For now the solution is to disable things you don't need, using `#undef ...` in the target file.

If this is still important, please try it and re-open this ticket if there's still an issue.

**Comment by rafaelmaeuer** [comment]
I experienced the same issue with Afroflight (Naze) rev. 6. Is there a working release out there or do I need to compile the firmware by myself to fit on 64kb flash???
